twitter:
    consumer:
        key: "cKelrTV6AWappfmRyn6ESCAzc"
        secret: "QUjMU3io6C7jN9OhRGnBfbq8GEn6ofKjTPAherxIOW6vz3yLnm"
    access_token:
        key: "1068156971000324097-DVbfd9hNUVfSs91jLnxpHqVAYttKAe"
        secret: "rSn4CgmiVpHI3jumz7qhmZ5LvaP4NHAEn1S4YFyXIHJwn"
